### ISSUE TITLE
API endpoints from GUI dashboard

### ISSUE THREAD

**Issue by tomaszwarda** [CiscoDevNet/catalystwan#205]
### Description

Cover API endpoints from GUI dashboard.

### Provider
- [x] /dataservice/network/connectionssummary #198 
- [x] /dataservice/clusterManagement/health/summary #198 
- [x] /dataservice/certificate/stats/summary #198 
- [x] /dataservice/device/control/count #198 
- [x] /dataservice/device/bfd/sites/summary #209 
- [x] /dataservice/device/tlocutil #209 
- [x] /dataservice/device/vedgeinventory/summary #209 
- [x] /dataservice/tenantstatus #209 
- [x] /dataservice/health/device #209 
- [x] /dataservice/alarms - already implemented in `alarms_api.py`
- [ ] /dataservice/event
### Provider as tenant and tenant
- [x] /dataservice/certificate/stats/summary #198 
- [x] /dataservice/msla/monitoring/licensedDeviceCount #217 
- [x] /dataservice/health/devices/overview #217 
- [x] /dataservice/device/bfd/sites/summary #209 
- [x] /dataservice/msla/monitoring/licensedDeviceCount #217 
- [x] /dataservice/device/vedgeinventory/summary #209 
- [x] /dataservice/statistics/approute/transport/summary/loss_percentage #217 
- [x] /dataservice/health/device #209 
- [x] /dataservice/statistics/approute/tunnels/health/latency #217 
- [x] /dataservice/alarms - already implemented in `alarms_api.py`
- [ ] /dataservice/event
